### ISSUE TITLE
Optimise failure scenario

### ISSUE THREAD

**Issue by PavelVlha** [keycloak/keycloak-benchmark#393]
- When killing a pod, wait for it to be up again to kill another
  - measure the time it takes for the pod to come up, and possibly also capture the log just after it became ready, so we have both the timing and the messages
- Save the logs before killing the pod (in .zip file using command line)
- Pulling all KC logs before end of the test run
- Capture the complete pod resource before killing and end of run
- Find bottlenecks

**Comment by ahus1** [comment]
@kami619 / @mhajas - when using the ec2 instances and some updated infrastructure, I was able to deliver the expected load in a "medium" sized scenario: 

Setup of the system: 
* 100000 clients 
* 10000 users
* 6 Keycloak pods, 15 DB connections for each pod
* kc-chaos.sh running continuouly
* 5 ec2 instances running the load against the cluster
* OpenShift loadbalancer configured for round-robin

Test 1: 
* 1000 client credential grants per second
* Measuring of 10 minutes

Results: works, still there some high peaks when a pod is restarted. Presumably due to a new pod being put into load-balancing with its full share. Due to that, requests queue up for that pod quite a bit. AFAIK there is no way for a slow-start of a pod.  

What didn't work: 
* Having only 3 pods of Keycloak running. This lead to overload scenarios (possibly the moment when they were put into the load balancing).
* Using "leastconn" routing instead of round-robin; it lead to a very uneven load balancing which increased over time. The hope was to have the same number of active connections on each pod, and any queue due to slow responses during startup would ensure that a new pod would get only parts of the load. It is unclear what a "connection" is meaning in the context of "leastconn" when used with TLS passthrough.

Test 2: 
* 280 authentication code per second
* 100% log out again
* Measuring of 10 minutes

Results: the latencies tend to building up, and there are *very* high peaks when a pod is restarted. Presumably due to a new pod being put into load-balancing with its full share, plus additional troubles as the other Keycloak instances try to connect to the pod that has just been terminated? As we're randomly starting pods, it seems that those pods which are not restarted build up a high JVM GC overhead (gradually up to 10+%), and at the end of the test we see the latencies increase.

Diagrams for the client credentials:

OK scenario:

![image](https://github.com/keycloak/keycloak-benchmark/assets/3957921/bf3acc5e-a57a-4cad-b9d0-e166e318e681)

![image](https://github.com/keycloak/keycloak-benchmark/assets/3957921/d0814d43-8af5-4a05-a894-7303a1406a68)

Scenario with "leastconn", where one Keycloak picks up a lot of requests, and things slow down/queue up:

![image](https://github.com/keycloak/keycloak-benchmark/assets/3957921/b9ad7714-0457-4f76-a210-38f2e87e34f1)

Diagrams for the authentication code: 

Not OK scenario, increased latencies after a pod restart, plus increasing latencies over time: 

![image](https://github.com/keycloak/keycloak-benchmark/assets/3957921/d51680bc-74d9-4f16-bad5-b1b8bf360d40)

![image](https://github.com/keycloak/keycloak-benchmark/assets/3957921/25f63503-b529-479e-ae01-ec9cc9a73b61)

Response time histogram over time:

![image](https://github.com/keycloak/keycloak-benchmark/assets/3957921/3c0971db-f340-45cf-af9f-ea7d0e9c2a47)

**Comment by ahus1** [comment]
Created a spin-off issue #410 to analyze the problems around user sessions.

**Comment by kami619** [comment]
thanks for the detailed analysis for the desired capacity runs for Keycloak @ahus1 

> Having only 3 pods of Keycloak running. This lead to overload scenarios (possibly the moment when they were put into the load balancing).

I am interested to know more about the sizing change from 3 to 6 Keycloak pods to accommodate for the overload, and where was the bottleneck observed. Does it mean we have hit the maximum capacity possible with 3 Keycloak pods in this case and what were the metrics achieved with that system ?

**Comment by ahus1** [comment]
> Does it mean we have hit the maximum capacity possible with 3 Keycloak pods in this case?

When using only three pods, and restarting one of them, this instance receives 1/3rd of the total load the moment it becomes ready. This is quite a peak, and with the JVM not being warmed up, this leads to a high spike of concurrent requests, which overloads the Pod. With 6 Pods, a restarting Pod receives only 1/6th of the load, which is a smaller peak. 

This is caused by the "roundrobin" strategy which we are using by default. As f my understanding of the docs, a "leastconn" distribution would deliver better results, as each Keycloak would process the same number of active session - still this didn't show up in the results. Maybe this only works with reencrypt and not passthrough. We might to get to an expert of this.

For the metrics, refer to the screen shots above. Please re-run the tests in a more controlled way than I did. For the Authentication Code scenario, there is an additional spinn-off issue as the results were not as good as anticipated.

**Comment by kami619** [comment]
> This is caused by the "roundrobin" strategy which we are using by default. As f my understanding of the docs, a "leastconn" distribution would deliver better results, as each Keycloak would process the same number of active session - still this didn't show up in the results. Maybe this only works with reencrypt and not passthrough. We might to get to an expert of this.

thanks @ahus1 for more detail on this. I agree that we might need more info on the ingress/load balancer configuration to understand this better.

**Comment by ahus1** [comment]
Thank you @kami619 - this resolves it for me. Added #438 as a follow-up as the cluster failures we've seen are troubling me.
