### ISSUE TITLE
Load Shedding for Keycloak

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#449]
Adjust the thread pool size of Keycloak. Create a list of max number of queued elements. Drive the discussion.
Have a meeting to create a shared understanding what strategies are available and why load shedding is a good thing.

**Comment by kami619** [comment]
We are going to be restricting the number of worker thread in Keycloak pod to minimize impact from jgroups thread pool congestion until ISPN-14780 is fixed, then we can scale  the worker threads a bit more as the total thread pool default will be 200 instead of the 100 which is now.

Keycloak PR: https://github.com/keycloak/keycloak-benchmark/pull/452
Keycloak Benchmark PR: https://github.com/keycloak/keycloak/commit/a1e1fd8d5da08068f39ea4a100ffc1a12763b1b0
