### ISSUE TITLE
Simplified image building for KC22 specific changes for Cross-DC actitivies

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#522]
### Description

When preparing changes to Keycloak 22 within the Keycloak Benchmark Project, it currently uses Keycloak main for the changes. 

With 

* the increasing number of changes to main which will never be backported to KC22
* eventually RESTEasy reactive keycloak/keycloak#15728 coming up and
* the need to stay on a productized Infinispan version in both KC 22 branch and KC main branch

there is the need have a KC 22 based with custom images necessary for the KCB to continue its tests. 

There might also be more of a need for one developer to prepare a change and another developer to run a load test for it.

To do this, the following seem to be are necessary to produce such images (to be reviewed and adjusted as needed):

* Have a new branch in KC repository based on KC22 which contains changes for KCB cross DC activities
* Have a nightly build of that branch published to a new org on Quay, tagged with the commit hash and a branch tag
* Have a GitHub action / workflow which allows to build a branch in the Keycloak repository or any other personal repository, and tag it with the commit hash
* For the existing regular workflows, and add an option to specify a repo + branch for the Keycloak deployment, and where the GHA would build the image on demand if it doesn't exist in that org
* Setup a cleanup mechanism which deletes commit hash based tags from the quay.io org (if there isn't such a mechanism build into Quay.io)

**Comment by kami619** [comment]
Is it possible to imprint the build image with the git sha information ? That would be great to narrow down on issues based on the sha commit, when there are backport changes to this release branch.

**Comment by mhajas** [comment]
Discussed privately:
- We don't want this feature in the main keycloak repository so the resulting workflow will be part of kcb repository
- There was a question about where to push images with the following options
  - Openshift (- we will lose images when OPC cluster restarts and we would need to have possibility to push to more clusters)
  - Quay - we would create keycloak-benchmark organization
  - Github container registry - I haven't investigated yet properly but I don't see an advantage against Quay

for now, a new org in Quay looks like the best option. 

Due to other priorities, I am pushing this issue back to backlog
