### ISSUE TITLE
Enhance handling of external Infinispan failure

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak-benchmark#591]
### Description

When in a A/P sync setup the Infinispan cluster on the active site fails, this is quite disastrous, and human intervention is required as the secondary site will be out of sync, and the LB check currently don't detect this. 

### Discussion

https://github.com/keycloak/keycloak-benchmark/pull/588#discussion_r1394320313

### Motivation

We should discuss if there is some automatic way to handle this. 

Possible ideas: 

* Make requests in Keycloak fail if the remote Infinispan is not available, to prevent the two site to get out-of-sync
* Have a probe in Keycloak (or Infinispan) which the loadbalancer can use to switch between DCs

**Comment by mhajas** [comment]
I tested this and the `lb-check` seems to work. How I tested it:

1. Had a running `rosa-cross-dc`
2. Logged in to ISPN console in dc1 and removed cache `sessions`
3. Observed the `lb-check` endpoint reports `DOWN` and AWS health check reports unhealthy
4. After some time (DNS switch) `client.****/lb-check` url reports `UP` because the load was switched to dc2
5. Create the `sessions` cache back
6. Observed `lb-check` on `primary.*****` reports `UP` again and AWS health check reports healthy again
