### ISSUE TITLE
re-run chaos tests using the new documentation around Multi-AZ A/P CrossDC cluster

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#607]
re-run chaos tests using the new documentation around Multi-AZ A/P CrossDC cluster

To provision
- https://www.keycloak.org/high-availability/introduction

To simulate failures
- https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/util/kc-failover

**Comment by tkyjovsk** [comment]
I tested the `kc-failover.sh` script with all the failure modes. Each run comprised of 15m  `AuthorizationCode` scenario at load injection rate of 100 users per second (moderate load). The specific failure mode was triggered approx. 5m into the run. The recovery operation was triggered after another 5m, leaving the remaining 5m for potential effects of the recovery to show in the results.

FAILOVER_MODE | Description | FAILURE INJECTION | RECOVERY PHASE
-- | -- | -- | --
HEALTH_PROBE | Deletes the Keycloak aws-health-route so that Route53 will eventually failover. | - No HTTP failures.<br>- CPU utilization showed transition of load from primary site to backup. | - No HTTP failures.<br>- CPU utilization showed transition of load from backup site back to primary.
KEYCLOAK_ROUTES | Deletes all Keycloak routes so that Route53 will eventually failover, but requests to the old DNS IP addresses will fail. The Keycloak Operator is scaled down to 0 pods to prevent the Keycloak Ingress from being recreated. | - Approx. 90s window after the failure injection with 100% of request failing.<br>- CPU utilization showed transition of load from primary site to backup. | - No HTTP failures.<br>- CPU utilization showed transition of load from backup site back to primary.
CLUSTER_FAIL | Deletes all Keycloak and Infinispan pods with no grace period and remove the associated StatefulSet. Both operators are scaled down to prevent the removed resources from being recreated. | - Approx. 90s window after the failure injection with 100% of request failing.<br>- CPU utilization showed transition of load from primary site to backup.<br>- Infinispan operator in the backup site didn’t show any issues with the cross-site replication even though the primary infinispan cluster was completely down. → **NOK** | - Recovery FAILED.<br>- Infinispan operator in the primary site was unable to bring the cluster back online. The first pod was started/ready but the second one ended up in a crash loop. Consequently the Keycloak cluster didn't start either.<br>- AWS healthcheck kept showing primary site as offline.<br>- CPU utilization showed the load kept going to the backup site for the rest of the run.
GOSSIP_ROUTER_FAIL | Deletes the Infinispan Gossip Router pod with no grace period and removes the associated Deployment. The Infinispan operator is scaled down to prevent the removed resources from being recreated. | - Approx. 90s window after the failure injection with 100% of request failing.<br>- CPU utilization showed transition of load from primary site to backup. | - Recovery FAILED.<br>- Infinispan operator in the primary site was unable to bring the gossip router back online.<br>- AWS healthcheck kept showing primary site as offline.<br>- CPU utilization showed the load kept going to the backup site for the rest of the run.

**Comment by tkyjovsk** [comment]
Due to above issue I was not able to test the manual recovery procedures yet:
- https://www.keycloak.org/high-availability/operate-network-partition-recovery
- https://www.keycloak.org/high-availability/operate-switch-back

**Comment by tkyjovsk** [comment]
Additionally I have also run a pod-level failure testing in the primary site under load.

A) Mild Load (50 users per second)
- negligible number of HTTP failures
- NO noticeable increase of request queue, or response times
 
B) Moderate Load (100 users per second)
- slightly higher but still negligible number of HTTP failures
- small increase in request queue during ~1m, short spike in response times for about 10s

C) Heavy Load (225 users per sec, maximum passing load for this setup)
- small but noticeable number of failed HTTP requests within a window of ~1m
- noticeable increase of request queue for about 3m
- initial spike in response times to over 5000ms and gradual reduction back to normal during next 3m

**Comment by ahus1** [comment]
Created issue for #663 to handle the expired tokens. Work on this issue can continue with the workaround to to replace the non-expired token with a longer duration.

**Comment by tkyjovsk** [comment]
After applying the workaournd I was able to move forward. Here are the results for the remaining two failure modes. The KC cluster behavior seems to work as expected. There are some issues with the Gossip router failover though.

FAILOVER_MODE | Description | FAILURE INJECTION RESULTS | RECOVERY RESULTS
-- | -- | -- | --
CLUSTER_FAIL | Deletes all Keycloak and Infinispan pods with no grace period and remove the associated StatefulSet. Both operators are scaled down to prevent the removed resources from being recreated. | - Approx. 60s window after the failure injection with 100% of request failing.<br>- CPU utilization showed transition of load from primary site to backup. | - Recovery successful.<br> - No HTTP failures under the load of 100 users per second.<br> - Low 100s of HTTP failures under the load of 225 users per second (near max load).<br> - CPU utilization showed transition of load from backup site back to primary.
GOSSIP_ROUTER_FAIL | Deletes the Infinispan Gossip Router pod with no grace period and removes the associated Deployment. The Infinispan operator is scaled down to prevent the removed resources from being recreated. | - Both sites **DOWN** after Gossip router failure. | - Recovery FAILED. Both sites remained down until load generation ended. After load stopped the Infinispan clusters in both sites recovered. Subsequent load run (within a few minutes) again showed a 100% HTTP success rate. (Diagnostic details were provided to the ISPN team.)

**Comment by ahus1** [comment]
Thank you very much for this test!

Here's the follow-up issue for the RHBK test: #674
